### ISSUE TITLE
'Go to issue' button isn't working

### ISSUE THREAD

**Issue by ARKEOLOGIST** [darensin01/goodfirstissues#13]
It seems that after a recent update, the 'Go to issue' button is no longer navigating to the issue being listed. 

Steps to reproduce:

1) Open goodfirstissues.com
2) Click on the 'Go to issue' button for any issue listed on site.

Expected behavior:

'Go to issue' button should properly navigate to the issue.

**Comment by darensin01** [comment]
Thanks for raising this issue! Will look into it.

**Comment by ARKEOLOGIST** [comment]
The issue seems to be fixed now, thanks for the help @darensin01
