### ISSUE TITLE
Navigation button heights are too long

### ISSUE THREAD

**Issue by Jwright707** [darensin01/goodfirstissues#26]
**Current Behavior:**
The navigation buttons are clickable below the displayed button.
![image](https://user-images.githubusercontent.com/40744027/101993002-d3f2bd00-3c6b-11eb-984f-527a4a9451b8.png)

**Desired Behavior:**
Reduce the height of the button to match the displayed button.

If this is a valid issue, can I please work on it? Thank you.

**Comment by darensin01** [comment]
Hi, please do work on it :)
