### ISSUE TITLE
Repository list goes blank at bottom

### ISSUE THREAD

**Issue by Jwright707** [darensin01/goodfirstissues#30]
I noticed when scrolling to the bottom of the repository list, that all the listings would disappear. 

![image](https://user-images.githubusercontent.com/40744027/103491144-1b391d00-4dd6-11eb-8c01-2ea3c327ee19.png)

**Comment by darensin01** [comment]
Hi @Jwright707 I can't seem to reproduce the problem... Mind letting me know what browser you're using and/or the steps that led to the problem?

**Comment by Jwright707** [comment]
Hi @darensin01 I'm currently using Brave. My screen resolution is 1900 by 1200 too.

**Comment by darensin01** [comment]
Hmm... I tried with Brave, but still can't get the same issue

**Comment by Jwright707** [comment]
Interesting, I just tried myself and it seems like it might have been fixed.

**Comment by Jwright707** [comment]
Going to close this issue because its not occurring anymore.
