### ISSUE TITLE
QUESTION: React does not appear in the programming languages filter

### ISSUE THREAD

**Issue by claudioantonio** [darensin01/goodfirstissues#31]
Why React does not appear in the programming language filter?
Is it a bug?

**Comment by darensin01** [comment]
Hey! React is a framework (not a programming language) in JavaScript (a programming language). Perhaps you can use other filters to filter for React?

**Comment by claudioantonio** [comment]
Thank You @darensin01 for the quick answer!
Yes, React is a framework and so is Vue. Vue is listed in the programming language filter but React don´t. 😔 
I did not find a good way to filter React projects other than filtering by JavaScript or TypeScript and checking each result...

**Comment by darensin01** [comment]
Actually, the programming language filter is based on this:
![image](https://user-images.githubusercontent.com/9928793/110052176-1ff85e00-7d92-11eb-9982-02c3329b34d9.png)
which can be found on every Github Repo.

Not sure why Vue is listed as a programming language though...

Perhaps you can search for React issues through the Issue label filter?

**Comment by claudioantonio** [comment]
Thank You for the explanation @darensin01 !
Well... I tried the Issue label filter but It lists a very small number of issues.
I would like to Thank You again for the attention!
