### ISSUE TITLE
`goodfirstissues.com` is not loading

### ISSUE THREAD

**Issue by shikharvashistha** [darensin01/goodfirstissues#33]
Greetings of the day @darensin01,

It's been 10+ minutes the website is not loading up.

Thanks & Regards
@shikharvashistha

**Comment by darensin01** [comment]
Seems to be loading on my side...

**Comment by shikharvashistha** [comment]
Greetings of the day @darensin01,

Yes it is now working for me too.

Thanks & Regards 
@shikharvashistha
